#!/usr/bin/env bash
# Install nginx and start it
sudo apt-get update
apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sed -i "48i location /redirect_me {\nreturn 301 https://www.nationalgeographic.com;\n}" /etc/nginx/sites-enabled/default
service nginx restart
