#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y update
sudo apt-get -y install haproxy=2.6.\*
echo -e 'frontend http_front\n\tbind *:80\n\tdefault_backend http_back' | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e 'backend http_back\n\tbalance roundrobin\n\tserver 137962-web-01 100.26.151.162:80 check' | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e '\n\tserver 137962-web-02 54.86.155.217:80 check' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy
sudo service haproxy start
