#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y update
sudo apt-get -y install haproxy=2.6.\*
echo "
frontend web-frontend
	bind *:80
	default_backend web-backend
backend web-backend
	balance roundrobin
	server 121493-web-01 34.201.61.125:80 check
	server 121493-web-02 54.236.54.193:80 check
" >> /etc/haproxy/haproxy.cfg

# Enable HAProxy management
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

sudo service haproxy restart
