#!/usr/bin/env bash
# Run NGINX as NGINX
pkill apache2
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
chmod 700 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
